services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_app
    volumes: # persistent storage
      - mysql:/var/lib/mysql # Where MySQL stores its data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s # Check every 5 seconds
      timeout: 5s # Fail if command takes >5s
      retries: 10 # Mark as unhealthy after 5 failures
      start_period: 30s # Wait 10s before first check (allow MySQl to start)

  app:
    image: flask-app
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/flask_app
      - ./app/logs:/flask_app/logs
    depends_on: # wait to confirm healthy MySQL check
      db:
        condition: service_healthy 
    networks:
      - backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_DATABASE: todo_app

  k6:
    image: grafana/k6
    depends_on:
      - app
    volumes:
      - ./loadtest:/scripts
      - ./artifacts/performance:/artifacts
    environment:
      - BASE_URL=http://app:5000
    command: run /scripts/k6_todos.js
    networks:
      - backend
  
networks:
  backend:

volumes:
  mysql:  