services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_app
    volumes: # persistent storage
      - mysql:/var/lib/mysql # Where MySQL stores its data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s # Check every 5 seconds
      timeout: 5s # Fail if command takes >5s
      retries: 10 # Mark as unhealthy after 5 failures
      start_period: 30s # Wait10s before first check (allow MySQl to start)

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/flask_app
      - ./app/logs:/flask_app/logs
    depends_on: # wait to confirm healthy MySQL check
      db:
        condition: service_healthy 
    networks:
      - backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_DATABASE: todo_app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  
networks:
  backend:

volumes:
  mysql:  